[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
solc_version = '0.8.30'
evm_version = 'prague'
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_limit = "18446744073709551615"

[profile.dev]
optimizer = false
via_ir = false

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.base_sepolia]
eth_rpc_url = "${BASE_SEPOLIA_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
local = "http://localhost:8545"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 84532 }
base-mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 8453 }

[fmt]
sort_imports = true
quote_style = 'single'